# Generated by Django 2.1.7 on 2019-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hits',
            name='ul',
            field=models.CharField(default='pt-br', max_length=200),
            preserve_default=False,
        ),
    ]
